name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout main
        uses: actions/checkout@v2
      - name: setup
        run: pip install mkdocs mkdocs-material markdown-captions mkdocs-redirects mkdocs-monorepo-plugin mkdocs-markdownextradata-plugin pygithub
      - name: Build
        run: mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
